### PR TITLE
Add NAMESERVER variable for dig

### PR DESCRIPTION
**Pull request by sreboot**
This enables `$NAMESERVER` env variable for dig. Useful for cases where DNS is not allowed directly to 8.8.8.8.

### CODE REVIEW

**Comment by sreboot** [comment]
@bahamat, please could you comment if this could be merged. Thanks.

**Comment by bahamat** [comment]
The reason that we check 8.8.8.8 explicitly, is because we're looking to see what Let's Encrypt will discover remotely, which means that we need to verify that external cache has been flushed. Otherwise we would check the local CNS server.

Trying to resolve against an internal name server may not adequately reflect the outside world's view of DNS. We highly recommend allowing the headnode to query 8.8.8.8 directly.

**Comment by sreboot** [comment]
Fully aware of that. The issue is that this is also used in instances not just the headnode itself. And in some environments direct DNS out will never happen (would be the case for a lot of on-prem customers).

We have a PowerDNS setup which is integrated with CNS and also handles all other requests. So far this setup with the NAMESERVER variable worked for us.

Will look into PowerDNS rules and options for upstream queries to 8.8.8.8. Nevertheless this would still be required as direct out is often not an option.

**Comment by bahamat** [comment]
Ok, can you file a. Issue for this one as well?

**Comment by sreboot** [comment]
Yep, will do. Thanks

**Comment by bahamat** [comment]
@sreboot We had a little bit of a mixup with a version that got released but accidentally didn't get merged into master on github. That's been resolved now, so can you rebase this and resolve the merge conflict?

Otherwise, this looks good so it'll be ready to merge once that's fixed. Sorry for the extra trouble :-(

**Comment by sreboot** [comment]
@bahamat sorry for the lag, can you please review this again. Thanks.

**Review by bahamat — APPROVED** [review]

**Pull request merged**
